ca.nrc.cadc.tap.TapQuery.langValues = ADQL ADQL-2.0
ADQL = org.opencadc.tap.dialect.pg.PostgresAdqlQueryImpl
ADQL-2.0 = org.opencadc.tap.dialect.pg.PostgresAdqlQueryImpl
ca.nrc.cadc.tap.MaxRecValidator = org.opencadc.tap.impl.MaxRecValidatorImpl
ca.nrc.cadc.tap.db.DatabaseDataType = ca.nrc.cadc.tap.pg.PostgresDataTypeMapper
ca.nrc.cadc.tap.writer.format.FormatFactory = org.opencadc.tap.dialect.pg.writer.format.PostgresFormatFactory
ca.nrc.cadc.tap.UploadManager = org.opencadc.tap.impl.RubinUploadManagerImpl
ca.nrc.cadc.tap.ResultStore = org.opencadc.tap.impl.ResultStoreImpl
ca.nrc.cadc.tap.schema.TapSchemaDAO = org.opencadc.tap.impl.ALMATapSchemaDAO
ca.nrc.cadc.tap.TableWriter = org.opencadc.tap.impl.RubinTableWriter
