INSERT INTO TAP_SCHEMA.schemas11 (schema_name, utype, description, schema_index) VALUES ('alma', null, 'ALMA tables', 10);

INSERT INTO TAP_SCHEMA.tables11 (schema_name, table_name, table_type, utype, description, table_index) VALUES ('alma', 'alma.obscore', 'view', null, 'ObsCore-1.1 observation table', 10);

INSERT ALL
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'calib_level', 'obscore:ObsDataset.calibLevel', 'meta.code;obs.calib', null, 'calibration level (2 or 3). 2 if product_type = MOUS, 3 if product_type = GOUS', 'int', null, null, null, 1, 0, 1, 7, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 's_ra', 'obscore:Char.SpatialAxis.Coverage.Location.Coord.Position2D.Value2.C1', 'pos.eq.ra', 'deg', 'RA of central coordinates', 'double', null, null, null, 1, 0, 1, 10, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 's_dec', 'obscore:Char.SpatialAxis.Coverage.Location.Coord.Position2D.Value2.C2', 'pos.eq.dec', 'deg', 'DEC of central coordinates', 'double', null, null, null, 1, 0, 1, 11, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 's_fov', 'obscore:Char.SpatialAxis.Coverage.Bounds.Extent.diameter', 'phys.angSize;instr.fov', 'deg', 'size of the region covered (~diameter of minimum bounding circle)', 'double', null, null, null, 1, 0, 1, 12, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 's_region', 'obscore:Char.SpatialAxis.Coverage.Support.Area', 'phys.outline;obs.field', 'deg', 'region bounded by observation', 'char', '*', 'adql:REGION', null, 1, 1, 1, 13, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 's_resolution', 'obscore:Char.SpatialAxis.Resolution.refval.value', 'pos.angResolution', 'arcsec', 'typical spatial resolution', 'double', null, null, null, 1, 0, 1, 14, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 't_min', 'obscore:Char.TimeAxis.Coverage.Bounds.Limits.StartTime', 'time.start;obs.exposure', 'd', 'start time of observation (MJD)', 'double', null, null, null, 1, 1, 1, 17, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 't_max', 'obscore:Char.TimeAxis.Coverage.Bounds.Limits.StopTime', 'time.end;obs.exposure', 'd', 'end time of observation (MJD)', 'double', null, null, null, 1, 1, 1, 18, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 't_exptime', 'obscore:Char.TimeAxis.Coverage.Support.Extent', 'time.duration;obs.exposure', 's', 'exposure time of observation', 'double', null, null, null, 1, 1, 1, 19, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 't_resolution', 'obscore:Char.TimeAxis.Resolution.refval.value', 'time.resolution', 's', 'typical temporal resolution', 'double', null, null, null, 1, 0, 1, 20, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'em_min', 'obscore:Char.SpectralAxis.Coverage.Bounds.Limits.LoLimit', 'em.wl;stat.min', 'm', 'start spectral coordinate value', 'double', null, null, null, 1, 1, 1, 22, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'em_max', 'obscore:Char.SpectralAxis.Coverage.Bounds.Limits.HiLimit', 'em.wl;stat.max', 'm', 'stop spectral coordinate value', 'double', null, null, null, 1, 1, 1, 23, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'em_res_power', 'obscore:Char.SpectralAxis.Resolution.ResolPower.refval', 'spect.resolution', null, 'typical spectral resolution', 'double', null, null, null, 1, 0, 1, 24, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'access_url', 'obscore:Access.Reference', 'meta.ref.url', null, 'URL to download the data', 'char', '*', 'clob', null, 1, 0, 1, 30, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'access_format', 'obscore:Access.Format', 'meta.code.mime', null, 'Content format of the data', 'char', '128*', null, 128, 1, 0, 1, 31, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'access_estsize', 'obscore:Access.Size', 'phys.size;meta.file', 'kbyte', 'estimated size of the download', 'long', null, null, null, 1, 0, 1, 32, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'obs_publisher_did', 'obscore:Curation.PublisherDID', 'meta.ref.url;meta.curation', null, 'publisher dataset identifier', 'char', '256*', null, 256, 1, 1, 1, 1, 'caomPlaneURI')
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'obs_collection', 'obscore:DataID.Collection', 'meta.id', null, 'short name for the data collection', 'char', '128*', null, 128, 1, 0, 1, 2, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'facility_name', 'obscore:Provenance.ObsConfig.Facility.name', 'meta.id;instr.tel', null, 'telescope name', 'char', '128*', null, 128, 1, 0, 1, 3, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'instrument_name', 'obscore:Provenance.ObsConfig.Instrument.name', 'meta.id;instr', null, 'instrument name', 'char', '128*', null, 128, 1, 0, 1, 4, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'obs_id', 'obscore:DataID.observationID', 'meta.id', null, 'internal dataset identifier', 'char', '128*', null, 128, 1, 0, 1, 5, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'dataproduct_type', 'obscore:ObsDataset.dataProductType', 'meta.id', null, 'type of product', 'char', '128*', null, 128, 1, 0, 1, 6, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'target_name', 'obscore:Target.Name', 'meta.id;src', null, 'name of intended target', 'char', '32*', null, 32, 1, 0, 1, 9, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'pol_states', 'obscore:Char.PolarizationAxis.stateList', 'meta.code;phys.polarization', null, 'polarization states present in the data', 'char', '32*', null, 32, 1, 0, 1, 27, null)
    INTO TAP_SCHEMA.columns11 (table_name, column_name, utype, ucd, unit, description, datatype, arraysize, xtype, "size", principal, indexed, std, column_index, id) VALUES ('alma.obscore', 'o_ucd', 'obscore:Char.ObservableAxis.ucd', 'meta.ucd', null, 'UCD describing the observable axis (pixel values)', 'char', '32*', null, 32, 1, 0, 1, 29, null) 
SELECT 1 FROM DUAL;
