FROM images.opencadc.org/library/cadc-tomcat:1

LABEL org.opencontainers.image.source "https://github.com/lsst-sqre/lsst-tap-service"

RUN dnf update -y && dnf install -y zip unzip

# Copy start into container and set permissions
ADD docker/start.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start.sh

# Copy war into tomcat webapps
ADD docker/*.war /usr/share/tomcat/webapps/

# Run the start script to handle the datalink task
ENTRYPOINT ["/usr/local/bin/start.sh"]
