version: '3.2'
services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    networks:
      - tap-network
    volumes:
      - './proxy/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - lsst-tap-service
  lsst-tap-service:
    image: lsstdax/lsst-tap-service:dev
    depends_on:
      - mock-qserv
      - tap-schema-db
      - uws-db
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - tap-network
    environment:
      CATALINA_OPTS: "-Dqservuser.username=qsmaster -Dqservuser.password= -Dqservuser.driverClassName=com.mysql.cj.jdbc.Driver -Dqservuser.url=jdbc:mysql://mock-qserv:3306/ -Dqservuser.maxActive=100 -Dtapschemauser.username=TAP_SCHEMA -Dtapschemauser.maxActive=100 -Dtapschemauser.password=TAP_SCHEMA -Dtapschemauser.driverClassName=com.mysql.cj.jdbc.Driver -Dtapschemauser.url=jdbc:mysql://tap-schema-db:3306/ -Duws.username=postgres -Duws.driverClassName=org.postgresql.Driver -Duws.url=jdbc:postgresql://uws-db/ -Dtap.maxActive=100 -Dca.nrc.cadc.util.PropertiesReader.dir=/config/ -Dpath_prefix=/ -Dbase_url=http://localhost/tap -Dtomcat.connector.connectionTimeout=20000 -Dtomcat.connector.keepAliveTimeout=120000 -Dtomcat.connector.secure=false -Dtomcat.connector.scheme=http -Dtomcat.connector.proxyName=localhost -Dtomcat.connector.proxyPort=80 -Dgcs_bucket=async-results.lsst.codes -Dgcs_bucket_url=https://tap-files.lsst.codes -Dgcs_bucket_type=GCS"
      GOOGLE_APPLICATION_CREDENTIALS: "/etc/google_creds.json"
    volumes:
      - './google_creds.json:/etc/google_creds.json'
  uws-db:
    image: lsstdax/uws-db:dev
    networks:
      - tap-network
  tap-schema-db:
    image: lsstdax/tap-schema-db:dev
    networks:
      - tap-network
    environment:
      MYSQL_DATABASE: "TAP_SCHEMA"
      MYSQL_USER: "TAP_SCHEMA"
      MYSQL_PASSWORD: "TAP_SCHEMA"
      MYSQL_ROOT_HOST: "%"
  mock-qserv:
    image: lsstdax/mock-qserv:dev
    networks:
      - tap-network

networks:
  tap-network:
